[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'bundle exec rails db:prepare && bundle exec puma -C config/puma.rb'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10